name: Welcome

# This workflow demonstrates GitHub Actions
# It runs whenever someone opens a pull request or pushes to main

on:
  pull_request:
    types: [opened]
  push:
    branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Greet contributor
        run: |
          echo "👋 Welcome to the CSSC GitHub Workshop!"
          echo "🎉 Thanks for contributing to this repository!"
          echo "📚 This workflow demonstrates GitHub Actions in action."
      
      - name: Display repository info
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Event: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Ref: ${{ github.ref }}"
